spring.application.name=app
# --- Database Configuration ---

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=bassel
spring.datasource.password=fl studio
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA & Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update
# Use 'validate' in production, 'create' for first run
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false 
# Recommended for performance

# --- Hibernate Envers (Auditing/History) Configuration ---
# Creates history tables with a _AUD suffix
org.hibernate.envers.audit_table_suffix=_HISTORY
org.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.org.hibernate.envers.enabled=false

app.jwt.secret=y1A8bS3wKjSmxV7z/B?E(H+MbQeThVmYq3t6w9z$C&F)J@NcRfUjXnZr4u7x!A%D
app.jwt.expirationMs=86400000


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.mine.profile.website.service.AppointmentService=DEBUG
logging.level.mine.profile.website.service=DEBUG
# Server Error Handling
server.error.include-message=always
server.error.include-binding-errors=always

logging.level.mine.profile.website.services=INFO
# Multipart Properties
spring.servlet.multipart.enabled=true


# Set the root logging level to INFO (the default)
logging.level.root=INFO

# Set the logging level for Spring Security to DEBUG to see authentication flow details
logging.level.org.springframework.security=DEBUG

# Set the logging level for all web requests to TRACE to see headers, etc.
logging.level.org.springframework.web=TRACE

# Set the logging level for Hibernate to DEBUG to see more details besides just the SQL
logging.level.org.hibernate=DEBUG

# Set the logging level for our own application code to DEBUG
logging.level.com.ecommerce.app=DEBUG